"""
===============================================================
ORATORIQ — MODEL EVALUATION & THRESHOLD ANALYSIS
===============================================================

This script does NOT retrain the models.

It analyzes the predictions already generated by:

    artifacts/results/temporal_predictions.csv

It checks:

1. Temporal flaw detection
2. Probability threshold performance
3. Flaw-type classification
4. Severity classification
5. Confusion matrices
6. Per-class precision / recall / F1

===============================================================
"""

from pathlib import Path

import numpy as np
import pandas as pd

from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    classification_report,
    confusion_matrix,
)


# ===============================================================
# PATHS
# ===============================================================

ROOT = Path(r"D:\OratorIQ")

PREDICTIONS = (
    ROOT
    / "artifacts"
    / "results"
    / "temporal_predictions.csv"
)

RESULTS_DIR = (
    ROOT
    / "artifacts"
    / "results"
)

RESULTS_DIR.mkdir(
    parents=True,
    exist_ok=True
)


# ===============================================================
# HELPERS
# ===============================================================

def print_header(title):

    print()
    print("=" * 70)
    print(title)
    print("=" * 70)


def print_confusion_matrix(
    cm,
    labels
):

    print()

    header = "Actual \\ Predicted"

    print(
        f"{header:<22}",
        end=""
    )

    for label in labels:

        print(
            f"{label:<18}",
            end=""
        )

    print()

    print("-" * (
        22 + 18 * len(labels)
    ))

    for i, label in enumerate(labels):

        print(
            f"{label:<22}",
            end=""
        )

        for value in cm[i]:

            print(
                f"{value:<18}",
                end=""
            )

        print()


# ===============================================================
# LOAD DATA
# ===============================================================

print_header(
    "ORATORIQ — MODEL EVALUATION"
)

print(
    f"Loading:\n{PREDICTIONS}"
)

if not PREDICTIONS.exists():

    raise FileNotFoundError(
        f"\nPrediction file not found:\n{PREDICTIONS}"
    )


df = pd.read_csv(PREDICTIONS)

print(
    f"\nPrediction rows: {len(df):,}"
)


# ===============================================================
# BASIC DATA CHECK
# ===============================================================

required_columns = [
    "temporal_label",
    "flaw_probability",
    "predicted_flaw",
    "flaw_type",
    "predicted_flaw_type",
    "recording_label",
    "predicted_severity",
]


missing = [
    column
    for column in required_columns
    if column not in df.columns
]


if missing:

    print(
        "\nMissing columns:"
    )

    for column in missing:

        print(
            f"  - {column}"
        )

    raise RuntimeError(
        "\nThe prediction CSV does not contain "
        "the required columns."
    )


# ===============================================================
# 1. TEMPORAL DETECTOR
# ===============================================================

print_header(
    "1. TEMPORAL FLAW DETECTION"
)


# Ground truth
df["actual_flawed"] = (
    df["temporal_label"] == "flawed"
).astype(int)


# Existing prediction
df["predicted_flawed_current"] = (
    df["predicted_flaw"]
    .astype(bool)
    .astype(int)
)


y_true = df["actual_flawed"]

y_pred = df["predicted_flawed_current"]


accuracy = accuracy_score(
    y_true,
    y_pred
)

precision = precision_score(
    y_true,
    y_pred,
    zero_division=0
)

recall = recall_score(
    y_true,
    y_pred,
    zero_division=0
)

f1 = f1_score(
    y_true,
    y_pred,
    zero_division=0
)


print(
    f"\nCurrent threshold: 0.50"
)

print(
    f"Accuracy : {accuracy:.4f}"
)

print(
    f"Precision: {precision:.4f}"
)

print(
    f"Recall   : {recall:.4f}"
)

print(
    f"F1       : {f1:.4f}"
)


# ===============================================================
# 2. THRESHOLD SWEEP
# ===============================================================

print_header(
    "2. FLAW PROBABILITY THRESHOLD ANALYSIS"
)

print(
    "Testing different thresholds..."
)

thresholds = np.arange(
    0.10,
    0.91,
    0.05
)

threshold_results = []


for threshold in thresholds:

    predictions = (
        df["flaw_probability"]
        >= threshold
    ).astype(int)

    acc = accuracy_score(
        y_true,
        predictions
    )

    prec = precision_score(
        y_true,
        predictions,
        zero_division=0
    )

    rec = recall_score(
        y_true,
        predictions,
        zero_division=0
    )

    score = f1_score(
        y_true,
        predictions,
        zero_division=0
    )

    threshold_results.append({

        "threshold": round(
            float(threshold),
            2
        ),

        "accuracy": acc,

        "precision": prec,

        "recall": rec,

        "f1": score,

    })


threshold_df = pd.DataFrame(
    threshold_results
)


print()

print(
    f"{'Threshold':<12}"
    f"{'Accuracy':<12}"
    f"{'Precision':<12}"
    f"{'Recall':<12}"
    f"{'F1':<12}"
)

print("-" * 60)


for _, row in threshold_df.iterrows():

    print(
        f"{row['threshold']:<12.2f}"
        f"{row['accuracy']:<12.4f}"
        f"{row['precision']:<12.4f}"
        f"{row['recall']:<12.4f}"
        f"{row['f1']:<12.4f}"
    )


best_row = threshold_df.loc[
    threshold_df["f1"].idxmax()
]


print_header(
    "BEST THRESHOLD BY F1"
)

print(
    f"Threshold : "
    f"{best_row['threshold']:.2f}"
)

print(
    f"Accuracy  : "
    f"{best_row['accuracy']:.4f}"
)

print(
    f"Precision : "
    f"{best_row['precision']:.4f}"
)

print(
    f"Recall    : "
    f"{best_row['recall']:.4f}"
)

print(
    f"F1        : "
    f"{best_row['f1']:.4f}"
)


threshold_path = (
    RESULTS_DIR
    / "threshold_analysis.csv"
)

threshold_df.to_csv(
    threshold_path,
    index=False
)

print(
    f"\nSaved:\n{threshold_path}"
)


# ===============================================================
# 3. TEMPORAL CONFUSION MATRIX
# ===============================================================

print_header(
    "3. TEMPORAL CONFUSION MATRIX"
)

cm = confusion_matrix(
    y_true,
    y_pred,
    labels=[0, 1]
)

print_confusion_matrix(
    cm,
    [
        "normal",
        "flawed"
    ]
)


# ===============================================================
# 4. FLAW TYPE CLASSIFICATION
# ===============================================================

print_header(
    "4. FLAW TYPE CLASSIFICATION"
)


# IMPORTANT:
# Only evaluate flaw type on windows that ACTUALLY
# contain a flaw.

flawed_df = df[
    df["temporal_label"] == "flawed"
].copy()


print(
    f"Actual flawed windows: "
    f"{len(flawed_df):,}"
)


actual_types = (
    flawed_df["flaw_type"]
    .fillna("unknown")
)

predicted_types = (
    flawed_df["predicted_flaw_type"]
    .fillna("unknown")
)


flaw_type_f1 = f1_score(
    actual_types,
    predicted_types,
    average="macro",
    zero_division=0
)

flaw_type_accuracy = accuracy_score(
    actual_types,
    predicted_types
)


print(
    f"\nFlaw-type Accuracy: "
    f"{flaw_type_accuracy:.4f}"
)

print(
    f"Flaw-type Macro F1: "
    f"{flaw_type_f1:.4f}"
)


print(
    "\nDetailed classification report:"
)

print(
    classification_report(
        actual_types,
        predicted_types,
        zero_division=0
    )
)


# Confusion matrix

flaw_labels = sorted(
    actual_types.unique()
)


flaw_cm = confusion_matrix(
    actual_types,
    predicted_types,
    labels=flaw_labels
)


print(
    "\nFlaw-type confusion matrix:"
)

print_confusion_matrix(
    flaw_cm,
    flaw_labels
)


# ===============================================================
# 5. FLAW TYPE PER-CLASS PERFORMANCE
# ===============================================================

print_header(
    "5. FLAW TYPE PERFORMANCE"
)

flaw_report = classification_report(
    actual_types,
    predicted_types,
    output_dict=True,
    zero_division=0
)


for flaw_type in flaw_labels:

    if flaw_type not in flaw_report:
        continue

    metrics = flaw_report[flaw_type]

    print(
        f"\n{flaw_type}"
    )

    print(
        f"  Precision: "
        f"{metrics['precision']:.4f}"
    )

    print(
        f"  Recall:    "
        f"{metrics['recall']:.4f}"
    )

    print(
        f"  F1:        "
        f"{metrics['f1-score']:.4f}"
    )

    print(
        f"  Samples:   "
        f"{int(metrics['support'])}"
    )


# ===============================================================
# 6. SEVERITY CLASSIFICATION
# ===============================================================

print_header(
    "6. SEVERITY CLASSIFICATION"
)


severity_df = df[
    df["temporal_label"] == "flawed"
].copy()


actual_severity = (
    severity_df["recording_label"]
    .fillna("unknown")
)

predicted_severity = (
    severity_df["predicted_severity"]
    .fillna("unknown")
)


severity_accuracy = accuracy_score(
    actual_severity,
    predicted_severity
)


severity_f1 = f1_score(
    actual_severity,
    predicted_severity,
    average="macro",
    zero_division=0
)


print(
    f"Severity Accuracy: "
    f"{severity_accuracy:.4f}"
)

print(
    f"Severity Macro F1: "
    f"{severity_f1:.4f}"
)


print(
    "\nSeverity classification report:"
)

print(
    classification_report(
        actual_severity,
        predicted_severity,
        zero_division=0
    )
)


severity_labels = [
    "slight",
    "medium",
    "bad",
    "extreme"
]


severity_cm = confusion_matrix(
    actual_severity,
    predicted_severity,
    labels=severity_labels
)


print(
    "\nSeverity confusion matrix:"
)

print_confusion_matrix(
    severity_cm,
    severity_labels
)


# ===============================================================
# 7. RECORDING-LEVEL ANALYSIS
# ===============================================================

print_header(
    "7. RECORDING-LEVEL FLAW DETECTION"
)


# A recording should be considered flawed if at least
# one temporal window is confidently detected as flawed.

recording_results = []


for record_id, group in df.groupby(
    "record_id"
):

    actual = (
        (group["recording_label"] != "good")
        .any()
    )

    max_probability = (
        group["flaw_probability"]
        .max()
    )

    predicted = (
        max_probability >= 0.50
    )

    recording_results.append({

        "record_id": record_id,

        "actual_flawed": int(actual),

        "max_probability":
            float(max_probability),

        "predicted_flawed":
            int(predicted),

    })


recording_df = pd.DataFrame(
    recording_results
)


recording_accuracy = accuracy_score(
    recording_df["actual_flawed"],
    recording_df["predicted_flawed"]
)

recording_precision = precision_score(
    recording_df["actual_flawed"],
    recording_df["predicted_flawed"],
    zero_division=0
)

recording_recall = recall_score(
    recording_df["actual_flawed"],
    recording_df["predicted_flawed"],
    zero_division=0
)

recording_f1 = f1_score(
    recording_df["actual_flawed"],
    recording_df["predicted_flawed"],
    zero_division=0
)


print(
    f"Recording Accuracy : "
    f"{recording_accuracy:.4f}"
)

print(
    f"Recording Precision: "
    f"{recording_precision:.4f}"
)

print(
    f"Recording Recall   : "
    f"{recording_recall:.4f}"
)

print(
    f"Recording F1       : "
    f"{recording_f1:.4f}"
)


recording_path = (
    RESULTS_DIR
    / "recording_level_predictions.csv"
)

recording_df.to_csv(
    recording_path,
    index=False
)


# ===============================================================
# 8. FINAL SUMMARY
# ===============================================================

print_header(
    "ORATORIQ — EVALUATION SUMMARY"
)

print(
    f"""
Temporal detector
-----------------
Accuracy : {accuracy:.4f}
Precision: {precision:.4f}
Recall   : {recall:.4f}
F1       : {f1:.4f}

Best threshold
--------------
Threshold: {best_row['threshold']:.2f}
F1       : {best_row['f1']:.4f}
Recall   : {best_row['recall']:.4f}

Flaw type
---------
Accuracy : {flaw_type_accuracy:.4f}
Macro F1 : {flaw_type_f1:.4f}

Severity
--------
Accuracy : {severity_accuracy:.4f}
Macro F1 : {severity_f1:.4f}

Recording level
---------------
Accuracy : {recording_accuracy:.4f}
Precision: {recording_precision:.4f}
Recall   : {recording_recall:.4f}
F1       : {recording_f1:.4f}
"""
)


print(
    "Evaluation complete."
)

print(
    f"\nResults saved in:\n{RESULTS_DIR}"
)